<a href="https://colab.research.google.com/github/AshishNalawade0188/My_DS_Work/blob/main/2SPandas_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

# Markdown Cell

In [ ]:
df=pd.read_csv("/content/sample_data/california_housing_train.csv") # dataset available in sample_data

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample_data/california_housing_train.csv'

In [ ]:
df.head(15)

In [ ]:
df.tail(10)

In [ ]:
# First upload Salaries.csv
#df=pd.read_csv("/content/Salaries.csv")
df=pd.read_csv(r"C:\Users\ashis\OneDrive\Documents\data science\21stJune24-main\My_Datasets-main\Salaries.csv")

In [ ]:
df

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [ ]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [ ]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [ ]:
df.tail(10)

         rank discipline  phd  service     sex  salary
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

In [ ]:
df['rank']

0          Prof
1          Prof
2          Prof
3          Prof
4          Prof
        ...
73         Prof
74    AssocProf
75         Prof
76         Prof
77         Prof
Name: rank, Length: 78, dtype: object

In [ ]:
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [ ]:
df.max()

rank            Prof
discipline         B
phd               56
service           51
sex             Male
salary        186960
dtype: object

In [ ]:
df.min()

rank          AssocProf
discipline            A
phd                   1
service               0
sex              Female
salary            57800
dtype: object

In [ ]:
df.phd.mean()

np.float64(19.705128205128204)

In [ ]:
df.phd.describe()

count    78.000000
mean     19.705128
std      12.498425
min       1.000000
25%      10.250000
50%      18.500000
75%      27.750000
max      56.000000
Name: phd, dtype: float64

In [ ]:
df.phd.quantile(0.25)

np.float64(10.25)

In [ ]:
df.salary.quantile(0.50)

np.float64(104671.0)

In [ ]:
df.salary.quantile(0.75)

np.float64(126774.75)

In [ ]:
df.phd.std()

np.float64(12.498424809175864)

In [ ]:
df_50=df.head(50)
df_50

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
20   AsstProf          B    4        4    Male   92000
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960

In [ ]:
df_50.salary.mean()

np.float64(113789.14)

In [ ]:
df_50

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
20   AsstProf          B    4        4    Male   92000
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960

In [ ]:
#Selecting a column
df.salary # does not work if column name contains blank space or dot (eg. "No. of Columns")
#           for that enclose column name inside square bracket.

0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [ ]:
df['salary'] # will work if column name has blank space or dot eg. df["No. of Columns"]

0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [ ]:
result1=df.salary
result1

0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [ ]:
# 2 data structures in pandas: 1. Series 2. DataFrame
# Pandas Series: is a one-dimensional labeled array whose object size cannot be changed.
#
# Pandas DataFrame: is a two-dimensional structure with columns and rows whose size can be changed.
# You can also think of it as a dictionary of Series objects.
type(result1)

pandas.core.series.Series

In [ ]:
result2=df[['salary','rank']]

In [ ]:
result2

    salary       rank
0   186960       Prof
1    93000       Prof
2   110515       Prof
3   131205       Prof
4   104800       Prof
..     ...        ...
73  105450       Prof
74  104542  AssocProf
75  124312       Prof
76  109954       Prof
77  109646       Prof

[78 rows x 2 columns]

In [ ]:
type(result2)

pandas.core.frame.DataFrame

In [ ]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [ ]:
# Extract particular columns in a new dataframe
newdf=df[['salary','service','phd']]
newdf

    salary  service  phd
0   186960       49   56
1    93000        6   12
2   110515       20   23
3   131205       31   40
4   104800       18   20
..     ...      ...  ...
73  105450       10   18
74  104542        6   19
75  124312       17   17
76  109954       14   28
77  109646       15   23

[78 rows x 3 columns]

In [ ]:
df['discipline'].value_counts() # category and its value

discipline
B    42
A    36
Name: count, dtype: int64

In [ ]:
df['rank'].value_counts()

rank
Prof         46
AsstProf     19
AssocProf    13
Name: count, dtype: int64

In [ ]:
# in rank 3 values: Asso,Asst,Prof. Group by this and find mean of each category
df.groupby(['rank']).salary.mean() # group by rank and finds mean of all numeric columns

rank
AssocProf     91786.230769
AsstProf      81362.789474
Prof         123624.804348
Name: salary, dtype: float64

In [ ]:
df.groupby(["discipline"]).count()

            rank  phd  service  sex  salary
discipline
A             36   36       36   36      36
B             42   42       42   42      42

In [ ]:
df.groupby(["discipline","rank"]).count()

                      phd  service  sex  salary
discipline rank
A          AssocProf    5        5    5       5
           AsstProf     8        8    8       8
           Prof        23       23   23      23
B          AssocProf    8        8    8       8
           AsstProf    11       11   11      11
           Prof        23       23   23      23

In [ ]:
df.groupby(["discipline","rank","sex"]).count()

                             phd  service  salary
discipline rank      sex
A          AssocProf Female    4        4       4
                     Male      1        1       1
           AsstProf  Female    6        6       6
                     Male      2        2       2
           Prof      Female    8        8       8
                     Male     15       15      15
B          AssocProf Female    6        6       6
                     Male      2        2       2
           AsstProf  Female    5        5       5
                     Male      6        6       6
           Prof      Female   10       10      10
                     Male     13       13      13

In [ ]:
df.groupby(["discipline","rank","sex"]).mean() # avg sal of discipline B's Male Prof is: 137989.076923

                                   phd    service         salary
discipline rank      sex
A          AssocProf Female  18.500000  15.500000   72128.500000
                     Male    20.000000  17.000000   81285.000000
           AsstProf  Female   4.833333   2.500000   72933.333333
                     Male     3.000000   1.000000   79000.000000
           Prof      Female  26.500000  16.125000  109631.875000
                     Male    28.933333  22.733333  113164.400000
B          AssocProf Female  13.500000   8.833333   99435.666667
                     Male    10.500000   7.500000  113404.000000
           AsstProf  Female   6.600000   2.600000   84189.800000
                     Male     4.666667   2.000000   88224.000000
           Prof      Female  21.500000  17.900000  131836.200000
                     Male    29.538462  25.846154  137989.076923

In [ ]:
df.groupby('rank')[['salary','phd']].mean() # group by rank and find mean of specified columns only

                  salary        phd
rank
AssocProf   91786.230769  15.076923
AsstProf    81362.789474   5.052632
Prof       123624.804348  27.065217

In [ ]:
df[df.salary>120000]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [ ]:
df.shape

(78, 6)

In [ ]:
df.shape[0]

78

In [ ]:
df[df.salary>120000].shape[0] # count of prof having sal > 120000

25

In [ ]:
# Create a dataframe having all Males whose salary is > 1,50,000/-

newdf=df[(df['sex']=='Male') & (df['salary']>150000)]
newdf

    rank discipline  phd  service   sex  salary
0   Prof          B   56       49  Male  186960
13  Prof          B   35       33  Male  162200
14  Prof          B   25       19  Male  153750
15  Prof          B   17        3  Male  150480
19  Prof          A   29       27  Male  150500
27  Prof          A   45       43  Male  155865
31  Prof          B   22       21  Male  155750

In [ ]:
# newdf.count()
# OR
newdf.shape[0]

7

In [ ]:
#df[(df['service']>15) | (df['salary']>100000)]
df[(df['service']>15) | (df['salary']>100000)].shape[0]

54

In [ ]:
df # will display all records

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [ ]:
# to extract only particular index record - say 5th index record
df.iloc[5] # will raise error

rank            Prof
discipline         A
phd               20
service           20
sex             Male
salary        122400
Name: 5, dtype: object

In [ ]:
df.iloc[77] # iloc -> index location for row

rank            Prof
discipline         A
phd               23
service           15
sex           Female
salary        109646
Name: 77, dtype: object

In [ ]:
df.iloc[1:4, 0:3]  # row 1 to 3, col 0 to 2

   rank discipline  phd
1  Prof          A   12
2  Prof          A   23
3  Prof          A   40

In [ ]:
df.iloc[0:10,0:3] # 0 to 9 records, 0 to 2 columns

        rank discipline  phd
0       Prof          B   56
1       Prof          A   12
2       Prof          A   23
3       Prof          A   40
4       Prof          B   20
5       Prof          A   20
6  AssocProf          A   20
7       Prof          A   18
8       Prof          A   29
9       Prof          A   51

In [ ]:
df.iloc[0:2,] # rows 0 to 1 and all columns, Or df.iloc[0:2]

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000

In [ ]:
df.iloc[:,4] #all rows, index 4 column

0       Male
1       Male
2       Male
3       Male
4       Male
       ...
73    Female
74    Female
75    Female
76    Female
77    Female
Name: sex, Length: 78, dtype: object

In [ ]:
df.iloc[:,0:3]

         rank discipline  phd
0        Prof          B   56
1        Prof          A   12
2        Prof          A   23
3        Prof          A   40
4        Prof          B   20
..        ...        ...  ...
73       Prof          B   18
74  AssocProf          B   19
75       Prof          B   17
76       Prof          A   28
77       Prof          A   23

[78 rows x 3 columns]

In [ ]:
df.iloc[[10,20,22,24],] # only particular rows with all columns df.iloc[[10,20,22,24]]

        rank discipline  phd  service   sex  salary
10      Prof          B   39       33  Male  128250
20  AsstProf          B    4        4  Male   92000
22  AsstProf          A    4        2  Male   73000
24      Prof          A   30       23  Male   91100

In [ ]:
df.loc[:,['rank','sex']] # without mentioning index no. - mention col name

         rank     sex
0        Prof    Male
1        Prof    Male
2        Prof    Male
3        Prof    Male
4        Prof    Male
..        ...     ...
73       Prof  Female
74  AssocProf  Female
75       Prof  Female
76       Prof  Female
77       Prof  Female

[78 rows x 2 columns]

In [ ]:
df.loc[[0,1,2],['discipline','rank']]

  discipline  rank
0          B  Prof
1          A  Prof
2          A  Prof

In [ ]:
df.iloc[::5] # start value:0, end value:77, step value:5, all rows and columns with step value 5

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
5        Prof          A   20       20    Male  122400
10       Prof          B   39       33    Male  128250
15       Prof          B   17        3    Male  150480
20   AsstProf          B    4        4    Male   92000
25       Prof          B   35       31    Male   99418
30  AssocProf          B    9        7    Male  107008
35       Prof          B   28       23    Male  126933
40       Prof          A   39       36  Female  137000
45       Prof          B   25       25  Female  140096
50   AsstProf          B   10        5  Female   97032
55   AsstProf          A    2        0  Female   72500
60   AsstProf          B    3        3  Female   92000
65       Prof          A   36       19  Female  117555
70   AsstProf          A    8        3  Female   78500
75       Prof          B   17       17  Female  124312

In [ ]:
df.iloc[10:30:4]

        rank discipline  phd  service   sex  salary
10      Prof          B   39       33  Male  128250
14      Prof          B   25       19  Male  153750
18      Prof          A   19        7  Male  107300
22  AsstProf          A    4        2  Male   73000
26      Prof          A   38       19  Male  148750

In [ ]:
df.iloc[::-1] # all records in reverse order

         rank discipline  phd  service     sex  salary
77       Prof          A   23       15  Female  109646
76       Prof          A   28       14  Female  109954
75       Prof          B   17       17  Female  124312
74  AssocProf          B   19        6  Female  104542
73       Prof          B   18       10  Female  105450
..        ...        ...  ...      ...     ...     ...
4        Prof          B   20       18    Male  104800
3        Prof          A   40       31    Male  131205
2        Prof          A   23       20    Male  110515
1        Prof          A   12        6    Male   93000
0        Prof          B   56       49    Male  186960

[78 rows x 6 columns]